### PR TITLE
Refactor code to works with ruby 3

### PR DESCRIPTION
**Pull request by LucianoPC**

### CODE REVIEW

**Comment by LucianoPC** [comment]
@davissp14 could you take a look at this MR, plz? I want to use this gem on ruby 3.0

**Comment by davissp14** [comment]
Hey there, I would go ahead and add your target ruby version here: https://github.com/davissp14/etcdv3-ruby/blob/master/.travis.yml#L2

**Comment by LucianoPC** [comment]
@davissp14 Hi, I have added to run tests for. ruby 3.0.2

**Comment by davissp14** [comment]
Awesome, i'll take a look here shortly.

**Comment by LucianoPC** [comment]
Hi, @davissp14 , I'm sending this ping because maybe you have forgotten, sorry if you are occupied

**Comment by davissp14** [comment]
Sorry, it has been a crazy week.  Merged and bumped the version.

**Pull request merged**
