### PR TITLE
Multiple endpoint / Basic HA support

### PR DESCRIPTION
**Pull request by davissp14**
**The Problem**
As of right now, the client only supports a single endpoint that's specified via `url`.  If the GRPC Proxy, HAProxy or Node you're targeting goes down, your application or service will go down with it.  Some people may configure DNS round-robin or handle failovers at the application / service level, but we could certainly make this process much easier on users.

**The Solution**
Allow users to specify multiple endpoints via an `endpoints` option. 
```ruby
conn = Etcdv3.new(endpoints: 'http://localhost:2379', 'http://localhost:23790')
```
With multiple endpoints available, we could recover from `GRPC::Unavailable` events and work to recover by cycling through the available endpoints.  I still need to do some digging on how this type of transition would affect Watches and determine whether or not we could properly recover these or not.

### CODE REVIEW

**Comment by mgates** [comment]
This is interesting - we're running a local GRPC proxy, which does a lot of this. I think that's the recommendation from etcd, it might be worth checking how that handles watches and whatnot.

https://coreos.com/etcd/docs/latest/op-guide/grpc_proxy.html

**Comment by davissp14** [comment]
Haha, I was actually just digging through that code.  The desired functionality is indeed pretty similar. 

Just to clarify, this isn't a replacement for the GRPC proxy.  It's really meant to be a general failover mechanism for the specified entry points.  For HA purposes, most people would want to have at least two entry points (GRPC Proxies in your case) running.

**Comment by davissp14** [comment]
This is working pretty well.  Should have some specs together in the next couple days.

**Comment by davissp14** [comment]
Here's the failover process at work.

I deployed an Etcd deployment at Compose.io, which is fronted with two HAProxy nodes.  I triggered the failover by manually tearing down the active endpoint.  As you can see below, the active watch stream and write loop successfully recovered.   

The recovery process took roughly 10 seconds as I currently attempt to recover the original connection before issuing the failover.

I am still working on fleshing out the logging. 

screen shot 2017-09-07 at 4 18 59 pm


Thoughts?

cc: @mgates

**Comment by mgates** [comment]
This is awesome - we did some work to start getting timeouts more controllable, which might make it simpler to get this to fail over faster too.

**Comment by davissp14** [comment]
Yeah, getting timeouts working will be super nice.

**Comment by davissp14** [comment]
Planning on getting this merged today.

**Pull request merged**
